### ISSUE TITLE
bug: Error during deploying Noto Cash Token

### ISSUE THREAD

**Issue by francescomiliani** [LF-Decentralized-Trust-labs/paladin#454]
### What happened?

Hello, I'm using [paladin-sdk@0.0.4-alpha.1](https://www.npmjs.com/package/@lfdecentralizedtrust-labs/paladin-sdk) and I'm trying to run Bond Issuance example in a Node.js express application.

I correctly & successfully ran the tutorial by downloading the Paladin repository a couple of days ago.

I'm experimenting this error on these lines
`
    // Create a Noto token to represent cash

    console.info("Deploying Noto cash token...");

    const notoFactory = new paladin.NotoFactory(paladin1, "noto");

    const notoCash = await notoFactory.newNoto(cashIssuer, {
      notary: cashIssuer,
      restrictMinting: true,
    });
    if (notoCash === undefined) {
      console.error("Failed!");
      throw new Error("Failed to deploy Noto cash token");
    }
`
notoCash will be undefined after a few seconds.

I receiced the error log
Failed while waiting for receipt: 33fa68f6-b8f4-4a9b-a2e4-95e430d13b39

A screenshot with states before the call

===
![image](https://github.com/user-attachments/assets/7517349e-16a7-4b12-bcee-74797f1e6e28)

### What did you expect to happen?

A correct deploy and a result with address below to these lines
===
    if (notoCash === undefined) {
      console.error("Failed!");
      throw new Error("Failed to deploy Noto cash token");
    }
    console.info(`Success! address: ${notoCash.address}`);

### How can we reproduce it (as minimally and precisely as possible)?

Install paladin-sdk via npm: npm i @lfdecentralizedtrust-labs/paladin-sdk@0.0.4-alpha.1

### OS version

Windows:
![image](https://github.com/user-attachments/assets/8c9efb9a-3a03-4c2a-b88a-42994dcb4f53)

Node version: 16.20.2

**Comment by hosie** [comment]
Hi @francescomiliani thanks for reporting this issue.

I could not reproduce it.  I followed the instructions in the REAME.md for the tutorial and I see the following output
```
Deploying Noto cash token...
Success! address: 0x6c4c987f744093620708f75b06158ca90bcc99a8
Issuing cash...
Success!
Creating issuer+custodian privacy group...
Success! address: 0x4c38c1a66f186625365cefc04d6191d5ccd6f644
Creating public bond tracker...
Success! address: 0x39e93eb94c784f9349c866c232454dbd5ffd0e28
Creating private bond tracker...
Success! address: 0xd88f57d342f588e8cfad43f94785d6f0bec37e97
Deploying Noto bond token...
Success! address: 0xd6df96f20532afdc38ef614eb1580243e57b3721
Issuing bond...
Success!
Beginning distribution...
Success!
Creating investor+custodian privacy group...
Success! address: 0x09683892492b44f9541168e2737f84185e135ec8
Creating private bond subscription...
Success! address: 0x2a10898276fbfa3650698bcb66140bf9d360b915
Preparing payment transfer...
Success!
Preparing bond transfer (step 1/2)...
Success!
Preparing bond transfer (step 2/2)...
Success!
Adding payment information to subscription request...
Success!
Adding bond information to subscription request...
Success!
Approving payment transfer...
Success!
Approving bond transfer...
Success!
Distributing bond...
Success!
```

Could you provide the logs from your paladin node pod during the time that you were seeing this error please? If possible, it would be useful to see logs from all 3 nodes.

**Comment by francescomiliani** [comment]
Hi @hosie thank you for your reply.

I deleted the cluster and re-created again and now it works 😃
